<a href="https://colab.research.google.com/github/rutyroot/MAI/blob/main/AA_ClasificadorIris_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Cargamos el dataset

In [1]:
from sklearn.datasets import load_iris

Asignamos el dataset en un objeto, es similar a un diccionario contiene keys y values

In [2]:
iris_dataset = load_iris()

DESCR es una descripción del dataset.

In [3]:
print(iris_dataset['DESCR'])

.. _iris_dataset:

Iris plants dataset
--------------------

**Data Set Characteristics:**

    :Number of Instances: 150 (50 in each of three classes)
    :Number of Attributes: 4 numeric, predictive attributes and the class
    :Attribute Information:
        - sepal length in cm
        - sepal width in cm
        - petal length in cm
        - petal width in cm
        - class:
                - Iris-Setosa
                - Iris-Versicolour
                - Iris-Virginica
                
    :Summary Statistics:

    ============== ==== ==== ======= ===== ====================
                    Min  Max   Mean    SD   Class Correlation
    ============== ==== ==== ======= ===== ====================
    sepal length:   4.3  7.9   5.84   0.83    0.7826
    sepal width:    2.0  4.4   3.05   0.43   -0.4194
    petal length:   1.0  6.9   3.76   1.76    0.9490  (high!)
    petal width:    0.1  2.5   1.20   0.76    0.9565  (high!)
    ============== ==== ==== ======= ===== ===========

target_names es un array de String que contiene las especies que queremos predecir.
features_names es una lista de String que da una descripción de cada característica.

In [5]:
print(iris_dataset['target_names'])

['setosa' 'versicolor' 'virginica']


Los datos están contenidos en los campos target y data.
data contiene un NumPy array con la longitud de pétalo y sépalo. Las filas se corresponden con cada flor encontrada y las columnas con los valores

In [6]:
print("Tipo de los Datos:", type(iris_dataset['data']))

Tipo de los Datos: <class 'numpy.ndarray'>


In [7]:
print("Forma de los datos:", iris_dataset['data'].shape)

Forma de los datos: (150, 4)


In [8]:
print("Primeras filas de datos: ", iris_dataset['data'][:5])

Primeras filas de datos:  [[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]]


target es un NumPy array que contiene las especies conocidas de cada flor, están codificadas con valores 0 a 2

In [9]:
print("Datos conocidos: ", iris_dataset['target'])

Datos conocidos:  [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2]


In [10]:
print("Valores de especies: ", iris_dataset['target_names'])

Valores de especies:  ['setosa' 'versicolor' 'virginica']


Particionamos el dataset en entrenamiento y pruebas

In [11]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(iris_dataset['data'], iris_dataset['target'], random_state=0)

In [12]:
print("X train shape:", X_train.shape)
print("y train shape:", y_train.shape)

X train shape: (112, 4)
y train shape: (112,)


In [13]:
print("X test shape:", X_test.shape)
print("y test shape: ", y_test.shape)

X test shape: (38, 4)
y test shape:  (38,)


In [14]:
print("X test:", X_test)

X test: [[5.8 2.8 5.1 2.4]
 [6.  2.2 4.  1. ]
 [5.5 4.2 1.4 0.2]
 [7.3 2.9 6.3 1.8]
 [5.  3.4 1.5 0.2]
 [6.3 3.3 6.  2.5]
 [5.  3.5 1.3 0.3]
 [6.7 3.1 4.7 1.5]
 [6.8 2.8 4.8 1.4]
 [6.1 2.8 4.  1.3]
 [6.1 2.6 5.6 1.4]
 [6.4 3.2 4.5 1.5]
 [6.1 2.8 4.7 1.2]
 [6.5 2.8 4.6 1.5]
 [6.1 2.9 4.7 1.4]
 [4.9 3.6 1.4 0.1]
 [6.  2.9 4.5 1.5]
 [5.5 2.6 4.4 1.2]
 [4.8 3.  1.4 0.3]
 [5.4 3.9 1.3 0.4]
 [5.6 2.8 4.9 2. ]
 [5.6 3.  4.5 1.5]
 [4.8 3.4 1.9 0.2]
 [4.4 2.9 1.4 0.2]
 [6.2 2.8 4.8 1.8]
 [4.6 3.6 1.  0.2]
 [5.1 3.8 1.9 0.4]
 [6.2 2.9 4.3 1.3]
 [5.  2.3 3.3 1. ]
 [5.  3.4 1.6 0.4]
 [6.4 3.1 5.5 1.8]
 [5.4 3.  4.5 1.5]
 [5.2 3.5 1.5 0.2]
 [6.1 3.  4.9 1.8]
 [6.4 2.8 5.6 2.2]
 [5.2 2.7 3.9 1.4]
 [5.7 3.8 1.7 0.3]
 [6.  2.7 5.1 1.6]]


Construcción del modelo con k nearest neighbors. Utilizaremos k=1
Cargamos la clase de scikit que contiene el algoritmo

In [15]:
from sklearn.neighbors import KNeighborsClassifier
knn = KNeighborsClassifier(n_neighbors=1)

El algortimo está encapsulado en el objeto knn.
Para construir el modelo con el conjunto de entrenamiento tenemos que llamar a la función fit que empareja datos con etiquetas.

In [16]:
knn.fit(X_train, y_train)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=None, n_neighbors=1, p=2,
                     weights='uniform')

Hacemos predicciones.
Utilizamos el modelo con nuevos datos (necesitamos hacerlo bidimensional pq scikit-learn siempre espera datos así)

In [17]:
import numpy as np
X_new = np.array([[5, 2.9, 1, 0.2]])
print("X new shape:", X_new.shape)

X new shape: (1, 4)


In [18]:
prediction = knn.predict(X_new)
print("Predicción:", prediction)
print("Especie predicha:", iris_dataset['target_names'][prediction])

Predicción: [0]
Especie predicha: ['setosa']


Evaluación del modelo

In [19]:
y_pred = knn.predict(X_test)
print("Predicciones para el conjunto de test: ", y_pred)

Predicciones para el conjunto de test:  [2 1 0 2 0 2 0 1 1 1 2 1 1 1 1 0 1 1 0 0 2 1 0 0 2 0 0 1 1 0 2 1 0 2 2 1 0
 2]


In [20]:
print("Porcentaje en el test: {:.2f}".format(np.mean(y_pred == y_test)))
print("Porcentaje en el test: {:.2f}".format(knn.score(X_test, y_test)))

Porcentaje en el test: 0.97
Porcentaje en el test: 0.97
